In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/raveendran2862/dataset/refs/heads/main/loan_approved.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  601 non-null    object
 2   Married                 611 non-null    object
 3   Dependents              599 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           582 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [ ]:
df.drop("Loan_ID",axis = 1,inplace = True)

In [ ]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area',
       'Loan_Status (Approved)'],
      dtype='object')

In [ ]:
x.Property_Area.unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [ ]:
# from sklearn.preprocessing import LabelEncoder,OneHotEncoder
# le = LabelEncoder()
# y1 = le.fit_transform(x['Property_Area'])
# y1

In [ ]:
# x = df.drop("Loan_Status (Approved)",axis = 1)
# y = df["Loan_Status (Approved)"]
# y

In [ ]:
# x["property_area"] = x.Property_Area.map({"Urban":1,"Semiurban":2,"Rural":3})   ##manual encoding
# x.head()

In [ ]:
# x1 = pd.get_dummies(x["Property_Area"],drop_first= True)
# x1

In [ ]:
# x2 = pd.concat([x1,x["Property_Area"]],axis = 1)
# x2

| Scenario         | Encoding           |
| ---------------- | ------------------ |
| Low cardinality  | One-Hot            |
| Ordinal category | Label              |
| High cardinality | Target / Frequency |
| Deep learning    | Embedding          |

In [ ]:
df.isnull().sum()

Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.shape

(480, 12)

In [ ]:
df["Dependents"].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [ ]:
df["Dependents"] = df["Dependents"].replace("3+",3)
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gender                  480 non-null    object
 1   Married                 480 non-null    object
 2   Dependents              480 non-null    object
 3   Education               480 non-null    object
 4   Self_Employed           480 non-null    object
 5   ApplicantIncome         480 non-null    int64
 6   CoapplicantIncome       480 non-null    float64
 7   LoanAmount              480 non-null    float64
 8   Loan_Amount_Term        480 non-null    float64
 9   Credit_History          480 non-null    float64
 10  Property_Area           480 non-null    object
 11  Loan_Status (Approved)  480 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 48.8+ KB

In [ ]:
df["Dependents"] = df["Dependents"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gender                  480 non-null    object
 1   Married                 480 non-null    object
 2   Dependents              480 non-null    int64
 3   Education               480 non-null    object
 4   Self_Employed           480 non-null    object
 5   ApplicantIncome         480 non-null    int64
 6   CoapplicantIncome       480 non-null    float64
 7   LoanAmount              480 non-null    float64
 8   Loan_Amount_Term        480 non-null    float64
 9   Credit_History          480 non-null    float64
 10  Property_Area           480 non-null    object
 11  Loan_Status (Approved)  480 non-null    object
dtypes: float64(4), int64(2), object(6)
memory usage: 48.8+ KB

In [ ]:
cat = df.select_dtypes(include='object')
cat.drop("Loan_Status (Approved)",axis = 1,inplace = True)
cat

     Gender Married     Education Self_Employed Property_Area
1      Male     Yes      Graduate            No         Rural
2      Male     Yes      Graduate           Yes         Urban
3      Male     Yes  Not Graduate            No         Urban
4      Male      No      Graduate            No         Urban
5      Male     Yes      Graduate           Yes         Urban
..      ...     ...           ...           ...           ...
609  Female      No      Graduate            No         Rural
610    Male     Yes      Graduate            No         Rural
611    Male     Yes      Graduate            No         Urban
612    Male     Yes      Graduate            No         Urban
613  Female      No      Graduate           Yes     Semiurban

[480 rows x 5 columns]

In [ ]:
num =df.select_dtypes(include=['int','float'])
num

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
1,1,4583,1508.0,128.0,360.0,1.0
2,0,3000,0.0,66.0,360.0,1.0
3,0,2583,2358.0,120.0,360.0,1.0
4,0,6000,0.0,141.0,360.0,1.0
5,2,5417,4196.0,267.0,360.0,1.0
...,...,...,...,...,...,...
609,0,2900,0.0,71.0,360.0,1.0
610,3,4106,0.0,40.0,180.0,1.0
611,1,8072,240.0,253.0,360.0,1.0
612,2,7583,0.0,187.0,360.0,1.0
613,0,4583,0.0,133.0,360.0,0.0

In [ ]:
cat

     Gender Married     Education Self_Employed Property_Area
1      Male     Yes      Graduate            No         Rural
2      Male     Yes      Graduate           Yes         Urban
3      Male     Yes  Not Graduate            No         Urban
4      Male      No      Graduate            No         Urban
5      Male     Yes      Graduate           Yes         Urban
..      ...     ...           ...           ...           ...
609  Female      No      Graduate            No         Rural
610    Male     Yes      Graduate            No         Rural
611    Male     Yes      Graduate            No         Urban
612    Male     Yes      Graduate            No         Urban
613  Female      No      Graduate           Yes     Semiurban

[480 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
encoded = ohe.fit_transform(cat).toarray()

# Get the feature names after one-hot encoding
encoded_columns = ohe.get_feature_names_out(cat.columns)

# Create the DataFrame with the correct column names
encoded = pd.DataFrame(encoded,columns=encoded_columns)
encoded

,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
475,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
476,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
477,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
478,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
479,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [ ]:
encoded.isnull().sum()

Gender_Female              0
Gender_Male                0
Married_No                 0
Married_Yes                0
Education_Graduate         0
Education_Not Graduate     0
Self_Employed_No           0
Self_Employed_Yes          0
Property_Area_Rural        0
Property_Area_Semiurban    0
Property_Area_Urban        0
dtype: int64

In [ ]:
num

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
1,1,4583,1508.0,128.0,360.0,1.0
2,0,3000,0.0,66.0,360.0,1.0
3,0,2583,2358.0,120.0,360.0,1.0
4,0,6000,0.0,141.0,360.0,1.0
5,2,5417,4196.0,267.0,360.0,1.0
...,...,...,...,...,...,...
609,0,2900,0.0,71.0,360.0,1.0
610,3,4106,0.0,40.0,180.0,1.0
611,1,8072,240.0,253.0,360.0,1.0
612,2,7583,0.0,187.0,360.0,1.0
613,0,4583,0.0,133.0,360.0,0.0

In [ ]:
encoded.shape

(480, 11)

In [ ]:
num.shape

(480, 6)

In [ ]:
X = pd.concat([encoded, num.reset_index(drop=True)], axis=1)
X

,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1,4583,1508.0,128.0,360.0,1.0
1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0,3000,0.0,66.0,360.0,1.0
2,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0,2583,2358.0,120.0,360.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0,6000,0.0,141.0,360.0,1.0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2,5417,4196.0,267.0,360.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0,2900,0.0,71.0,360.0,1.0
476,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,3,4106,0.0,40.0,180.0,1.0
477,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1,8072,240.0,253.0,360.0,1.0
478,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2,7583,0.0,187.0,360.0,1.0
479,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0,4583,0.0,133.0,360.0,0.0

In [ ]:
le = LabelEncoder()
y = le.fit_transform(df["Loan_Status (Approved)"])
y

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [ ]:
y_pred = lr.predict(X)
y_pred

array([ 0.7893972 ,  0.82345209,  0.73643967,  0.72821337,  0.72164476,
        0.75448061,  0.25592134,  0.80650956,  0.75618842,  0.855806  ,
        0.73497379,  0.68862673,  0.89863882,  0.73463698,  0.02308469,
        0.72786087,  0.09384424,  0.69773495,  0.18578588,  0.88870942,
        0.91513215,  0.77371424,  0.70966227,  0.75588294,  0.70911261,
        0.92404169,  0.63412258,  0.85335217,  0.6459856 ,  0.78001564,
        0.75349343,  0.75637883,  0.90976769,  0.86404126,  0.81040912,
        0.05725517,  0.76283812,  0.80768563,  0.79257376,  0.79660805,
        0.83482403,  0.01043698,  0.95604288,  0.93183683,  0.76941055,
        0.78668309,  0.74272536,  0.78618899,  0.85956081,  0.00903771,
        0.12230689,  0.83721874, -0.00297557,  0.75029231,  0.79875951,
        0.1136966 ,  0.77032467,  0.86778446,  0.87529503,  0.90391471,
        0.72718516,  0.67063363,  0.78744641,  0.23947173,  0.79685264,
        0.74299732,  0.87268608,  0.82284353,  0.92396692,  0.69954458,
        0.87693041,  0.90568239,  0.89740915,  0.77904545,  0.85178738,
        0.85545784,  0.84847847,  0.95687908,  0.89424658,  0.8995199 ,
        0.76254392,  0.80647456,  0.82951491,  0.78891102,  0.09502314,
        0.89659984,  0.73004537,  0.80080473,  0.84160533,  0.75364719,
        0.61963004,  0.82607601,  0.034142  ,  0.9732503 ,  0.68360297,
        0.1088116 ,  0.73854773,  0.87364851,  0.98184884,  0.86083922,
        0.8260684 ,  0.75169219,  0.80431216,  0.13254985,  0.73749848,
        0.77023322,  0.71621303,  0.82887824,  0.91698594,  0.83345026,
        0.84547028,  0.80807418,  0.85570257,  0.5951272 ,  0.92721519,
        0.04122276,  0.72876964,  0.68509051,  0.75592353,  0.7663374 ,
        0.12225436,  0.80392205,  0.82900407,  0.87332785,  0.75462   ,
        0.26196719,  0.78704321,  0.86016762,  0.73954534,  0.76170849,
        0.19184756,  0.92411137,  0.79885189,  0.85905797,  0.86256905,
        0.77976894,  0.80922997,  0.03449194,  0.94812224, -0.01617716,
        0.06986043,  0.97495932,  0.90048404,  0.88163059,  0.89280348,
        0.14231054,  0.78657833,  0.68114884,  0.83744397,  0.74128311,
        0.8716074 ,  0.71186151,  0.90193653,  0.65224171,  0.73643421,
        0.87481512,  0.18122499,  0.75180202,  0.89277987,  0.73093582,
        0.6937527 ,  0.65566403,  0.76205114,  0.84926595,  0.75520227,
        0.28002986,  0.76066241,  0.74116581,  0.78588213,  0.90494941,
        0.77130253,  0.91583994,  0.17254123,  0.94366086,  0.8174112 ,
        0.93381316,  0.77329239,  0.90417774,  0.65884032,  0.93485407,
        0.72574891,  0.92195423,  0.77378446,  0.66591526,  0.95658419,
        0.77345938,  0.75942159,  0.70125641,  0.79163376,  0.83389838,
        0.69838027,  0.84687486,  0.77997892,  0.91657201,  0.81562128,
        0.1312506 ,  0.68935212,  0.61748049,  0.77096107,  0.01920109,
        0.62419087, -0.01987955,  0.8628244 ,  0.70254185,  0.82635921,
        0.82049905,  0.65377905,  0.83028905,  0.6684043 ,  0.93212397,
        0.14546492,  0.68600883,  0.71544006,  0.81650381,  0.6924482 ,
        0.90315785,  0.96981066,  0.93205245,  0.86997157,  0.82553422,
        0.8043043 , -0.04510097,  0.93265578,  0.86750764,  0.68984474,
        0.69826383,  0.77314874,  0.77782277,  0.79525437,  0.68541605,
        0.76565439,  0.2814715 ,  0.82054342,  0.8838402 ,  0.91322168,
        0.76451428,  0.60509376,  0.80689229,  0.07022585,  0.6474891 ,
        0.82382797,  0.68136086,  0.63109656, -0.00580252,  0.5635932 ,
        0.80810786,  0.77277117,  0.67923057,  0.77542174,  0.956706  ,
        0.77405682,  0.91871975,  0.96397121,  0.75369255, -0.03832093,
        0.03534675,  0.87112718,  0.74355601,  0.69902567,  0.73257898,
        0.8616086 ,  0.73160241,  0.81436002,  0.72661588,  0.68350516,
        0.74107461,  0.92443931,  0.89671742,  0.75640524,  0.71128403,
        0.89182765,  0.59633086,  0.81844106,  0.05109509,  0.86710479,
        0.77110913,  0.85318926,  0.06673579,  0.90552274,  0.82063459,
        0.87514174,  0.79567614,  0.68464343,  0.64493039,  0.8501956 ,
        0.92379605,  0.56211481,  0.80761258,  0.94224586,  0.62405026,
        0.07840916,  0.83040254,  0.78093567,  0.74506984,  0.83694121,
        0.74040949,  0.66214083,  0.71502358,  0.84954914,  0.77037184,
        0.79115201,  0.793917  ,  0.71712149,  0.76182953,  0.90057846,
        0.83101817,  0.02509114,  0.81761044,  0.63972064,  0.11098695,
        0.1558582 ,  0.67875744,  0.68538359,  0.7587966 ,  0.60239093,
        0.79546282,  0.73803868,  0.6124581 ,  0.26824587,  0.08765406,
        0.74676134,  0.01904793,  0.71886961,  0.08757604,  0.70230632,
        0.66906533,  0.594541  ,  0.77325411,  0.91567795,  0.78844544,
        0.81258365,  0.95194814,  0.75688565,  0.61746541,  0.95215942,
        0.80899639,  0.71754458,  0.7732192 ,  0.04697226,  0.90508149,
        0.74489103,  0.8658455 ,  0.01849517,  0.64783327,  0.77933956,
        0.75531366,  0.79218415,  0.86565938,  0.77116485,  0.75839341,
        0.11528582,  0.06728861,  0.09514877,  0.13175007,  0.85032265,
        0.96718756,  0.82093928,  0.77445722,  0.72567134,  0.92095804,
        0.86740111,  0.76153319,  0.18968087,  0.70407666,  0.14091305,
        0.8031213 ,  0.89054353,  0.07829848,  0.97619759,  0.67457187,
        0.78096295,  0.90127824,  0.92854056,  0.57533539,  0.76665995,
        0.90437961,  0.89008715,  0.90431993,  0.71644648,  0.07703299,
        0.67247178,  0.90227002,  0.7550884 ,  0.65366384,  0.67231558,
        0.10430484,  0.91293651,  0.72323653,  0.93740654, -0.03663577,
        0.60950627,  0.80128606,  0.87021167,  0.86520132,  0.72403829,
        0.74408055,  0.72637751,  0.64676947,  0.87371279,  0.81040532,
        0.91710216,  0.59793778,  0.78328457,  0.87309482,  0.80808268,
        0.60046239,  0.91105966,  0.88004832,  0.80407939,  0.58010321,
        0.68180316,  0.94040217,  0.1821035 ,  0.79994648,  0.78733335,
        0.85974398,  0.06403871,  0.59989013,  0.69852472,  0.87871091,
        0.75129678,  0.82959795,  0.87193861,  0.12868236,  0.74169202,
        0.76261255,  0.83991522,  0.68469761,  0.12835749,  0.78156898,
        0.78519564,  0.03759626,  0.09843106,  0.9790421 ,  0.89006729,
        0.89469977,  0.82975777,  0.89749818,  0.66693917,  0.73896966,
        0.7665768 ,  0.11055785,  0.75770001,  0.13049696,  0.72412688,
        0.13597857,  0.7861283 ,  0.7795942 ,  0.84034666,  0.95535194,
        0.86913059,  0.71648852,  0.79083394,  0.9212228 ,  0.45417213,
        0.91263916,  0.10461402,  0.78494527,  0.8127958 ,  0.75152127,
        0.2703522 ,  0.95185357,  0.91361845,  0.77515489,  0.74575731,
        0.65373382,  0.69774603,  0.7528579 ,  0.81023631,  0.84829789,
        0.65166465,  0.72777242,  0.90149204,  0.72541181,  0.78323057,
        0.672917  ,  0.87921557,  0.77248164,  0.81329391,  0.09573301])

In [ ]:
from sklearn.metrics import r2_score
r2_score(y,y_pred)

0.3195602995575628

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X,y)

LogisticRegression()

In [ ]:
y_pred1 = lr.predict(X)
y_pred1

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred1)

0.8083333333333333